name: Conditionally Patch New Release
on:
  workflow_dispatch:
  schedule:
    - cron: "00 0 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release info
        id: getLatest
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: Get latest Fennec release version
        run: |
          version=$(curl -s https://f-droid.org/repo/index-v1.json | jq -r '(first(.packages."org.mozilla.fennec_fdroid".[] | select(.nativecode[] | contains("arm64-v8a")))) as $newestVersion | $newestVersion.versionName + "-" + ($newestVersion.versionCode | tostring)')
          echo "BUILD_VERSION=$version" >> $GITHUB_ENV
      - name: Check if latest version was already built
        if: ${{ steps.getLatest.outputs.tag_name == env.BUILD_VERSION }}
        run: |
          echo latest version already built and released
          exit -1
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign apksigner
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build script and sign apk
        run: |
          cd ${{ github.workspace }}
          chmod +x ./build.sh
          ./build.sh
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} patched_signed.apk
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BUILD_VERSION }}
          files: ${{ github.workspace }}/patched_signed.apk
