name: Force New Release
permissions:
  contents: write
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: Get latest Fennec release version
        run: |
          version=$(curl -s https://f-droid.org/repo/index-v1.json | jq -r '(first(.packages."org.mozilla.fennec_fdroid".[] | select(.nativecode[] | contains("arm64-v8a")))) as $newestVersion | $newestVersion.versionName + "-" + ($newestVersion.versionCode | tostring)')
          echo "BUILD_VERSION=$version" >> $GITHUB_ENV
      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y wget apktool zipalign apksigner
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run build script and sign apk
        run: |
          cd ${{ github.workspace }}
          chmod +x ./build.sh
          ./build.sh
          echo "${{ secrets.KEYSTORE }}" | base64 -di > keystore.jks
          apksigner sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSPHRASE }} patched_signed.apk
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BUILD_VERSION }}
          files: ${{ github.workspace }}/patched_signed.apk
